import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Banner from "@/components/layout/banner";
import Header from "@/components/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Banner />
        <Header />
        {children}
        <Toaster closeButton richColors position="top-right" />
      </body>
    </html>
  );
}
